Fix Venti bug, added test and an extra message
uzair-ashraf/genshin-impact-wish-simulator pull request #10
Opened 2020-10-19 05:33 UTC by lauslim12

Hello!

This PR addresses the following:
- I have fixed the Venti bug. We should now properly get him if our first SSR is not Venti.
- Also added test suite for the guaranteed SSR after a non-Venti SSR pull.
- Added an additional disclaimer message on the modal that people should not expect this tool to be the reflection of their gacha experience, as some people are simply hopeless and believed that if they got an SSR here, then they would also get them in the game as well 😂 (even I sometimes hope so every time I get an SSR from the gacha simulator!).

Oh, and I think I found a bug:
- When we receive an SSR that is not from the 90 pull, I believe the `attemptsCount` variable is not reset to zero, which is expected behavior from Genshin Impact's gacha. In other words, because of this bug, we are guaranteed to get an SSR every 90 `attemptsCount` is reached, even if we have gained one SSR beforehand.
- But I also notice that you use the `attemptsCount` variable to take note about how much times we have pulled. I propose a fix and that is to create a new variable to store how many times we have pulled from the gacha pool, but it will be reset every time we pulled an SSR. 

I think I can fix that if you want, what do you think?

Thank you very much!

Resolves #2

2020-10-19 16:59 UTC, uzair-ashraf commented
Reviewing now, as for the bug you found, I may have not understood properly

> When we receive an SSR that is not from the 90 pull, I believe the attemptsCount variable is not reset to zero, which is the expected behavior from Genshin Impact's gacha. In other words, because of this bug, we are guaranteed to get an SSR every 90 attemptsCount, even if we had gained one SSR beforehand.

Are you saying that we should not get a guaranteed 5 star pull every 90 attempts? It states atleast once per 90 attempts
![image](https://user-images.githubusercontent.com/52118958/96484577-3772e800-11f1-11eb-9ddc-cd0eb81ad07a.png)

The setter in the class sets the guaranteed5Star property dynamically.

![image](https://user-images.githubusercontent.com/52118958/96485328-69844a00-11f1-11eb-9775-e03bcc8a6c74.png)

Ah I believe it makes sense now, you want to reset the attempts count after recieving a 5 star to make sure the guarantee follows through,

The attempts count is used in the tests to provide further expandability in the future as well.

If you do update it, you will have to test the app vigorously to make sure it works properly but I like the idea.

2020-10-19 17:08 UTC, uzair-ashraf requested changes

2020-10-19 17:08 UTC, uzair-ashraf commented on src/models/ballad-in-goblets.js
> +      item = this.drops.find((el) => el.name === 'Venti');
use the `grabAVenti` method here, and for the sake of consitency drop the paranthesis when using a single parameter in arrow functions.

2020-10-19 17:08 UTC, uzair-ashraf commented on test/test.js
> +import { assert } from 'chai'
No need to import if just needed once

2020-10-19 17:08 UTC, uzair-ashraf commented on test/test.js
> +          assert.fail('The second SSR pulled was not Venti!');
For the sake of consistency use `expect.fail` instead.

2020-10-19 17:08 UTC, uzair-ashraf commented on test/test.js
> +
```
const roll = balladVenti.roll()
results.push(roll)
```

2020-10-19 17:08 UTC, uzair-ashraf commented on test/test.js
> +        const areNamesFilled = names.length > 0 ? true : false;
Drop paranthesis in one parameter arrow functions for the sake of consitency
```
        const filteredResults = roll.filter(item => item.rating === 5);
        const names = filteredResults.map(e => e.name);
        const areNamesFilled = names.length > 0;
```
No ternary needed, expressions using comparison operators always resolve to a boolean

2020-10-19 17:27 UTC, lauslim12 commented
Okay, code updated to your review! Thank you!

`Are you saying that we should not get a guaranteed 5 star pull every 90 attempts?`

I actually mean that the '90 attempt' counter should be reset if we pulled an SSR (because I notice a pattern where we'll get an SSR every 90 rolls, even if we had gotten an SSR in the middle of the count). I think Genshin Impact's gacha works like that? Every time we get an SSR, the counter will be reset back to zer.

`5-Star pity: If a player does not win a 5-star item 89 pulls in a row the 90th pull is guaranteed to be a 5-star item. This counter will reset if the player pulls any 5-star item.`

Source is from the [fandom wiki](https://genshin-impact.fandom.com/wiki/Wishes), but honestly, I actually believe that the gacha system is still extremely mysterious even to us...

2020-10-19 18:08 UTC, uzair-ashraf requested changes
Thank you for contributing by the way I should have mentioned this before.
I can approve after this small change, You can create a separate pr for the attemptsCounter change afterwards, but you will have to update the tests as well.

2020-10-19 18:08 UTC, uzair-ashraf commented on test/test.js
> +        const filteredResults = results[results.length - 1].filter(item => item.rating === 5);
Readability and helps make use of the roll variable 😅 
```
const filteredResults = roll.filter(item => item.rating === 5);
```

2020-10-20 00:15 UTC, lauslim12 commented
You're welcome! I always love contributing in open source projects!

I think I'll read more about the gacha before contributing the `attemptsCounter` so I can get a clearer picture on it. Do I have to make a new issue?

Thank you!

2020-10-20 16:39 UTC, uzair-ashraf commented
We'll hold off on it for now, till after I finish Klees banner and we can do a refactor.

2020-10-20 16:50 UTC, uzair-ashraf approved these changes

2020-10-20 16:51 UTC, merged